# Copyright (c) 2017-2019, Hans Erik Thrane

0123456789 = {
  broker = "0123"
  user = "0123"
  password = "abcdef"
  investor = "05853735"
  symbols = {
    GDAX = [ "${BTC}" ]
  }
  master = true  # reference data
}
