symbols = [
  ".*-PERPETUAL",
  ".*-DERIBIT-INDEX",
  ".*-\\d{2}\\D{3}\\d{2}",
]

[order_templates]

  [order_templates.default]
  self_trade_prevention = 'D'

[accounts]

  [accounts.A1]
  master = true
  login = "YOUR_DERIBIT_LOGIN_GOES_HERE"
  secret = "YOUR_DERIBIT_SECRET_GOES_HERE"
  symbols = [ "BTC-.*", "ETH-.*" ]

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "BTC-\\d{2}\\D{3}\\d{2}" ]
  monitor_period_secs = 60
  ban_period_secs = 300
  request_limit = 10
