# Copyright (c) 2017-2019, Hans Erik Thrane

# Local timestamps will be converted to UTC using this time-zone.
time_zone = America/Chicago

# Users allowed to access the gateway.
.include(key=users) ./users.conf

# Gateway will only process symbols defined in this config file.
.include(key=symbols) ./symbols.conf

# Account definitions.
.include(key=accounts) ./accounts.conf

# REST API connection details.
.include(key=rest_api) ./rest_api.conf

# Websocket API connection details.
.include(key=websocket_api) ./websocket_api.conf

# FIX API connection details.
.include(key=fix_api) ./fix_api.conf
