# Copyright (c) 2017-2019, Hans Erik Thrane

# This user can *not* trade.
test = {
  password = "1234"
  symbols = {
    GDAX = [ ".*" ]
  }
  limits = {
    create_order = {
      max = 0
    }
  }
}

trader = {
  password = "secret"
  accounts = [ "0123456789" ]
  symbols = {
    GDAX = [ "${BTC}" ]
  }
  limits = {
    create_order = {
      max = 10
      monitor_period = 60s
      ban_period = 300s
    }
  }
}
