symbols="BTC-PERPETUAL"
# [symbols]
#   include = ".*"
#   exclude = [".*USD[CT].*", "BTC-PBUT-24JUN22-40000_45000_50000"]  # workaround due to missing market data

[accounts]

  [accounts.A1]
  master = true
  login = "5MP40u9h"
  secret = "8XC2sDXtrGFtVdOFKCU2eg3uE1oOntCoJCM3abpNBmI"
  symbols = ".*"

#  [accounts.A2]
#  login = "5lsDhumZ"
#  secret = "G_zfAoiRpKe-kLsfhc5_L1XAnsCztRio-mZguE83Dr0"
#  symbols = ".*"

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "BTC-\\d{2}\\D{3}\\d{2}", "BTC-PERPETUAL" ]

  [users.maker]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "BTC-\\d{2}\\D{3}\\d{2}", "BTC-PERPETUAL" ]

[rate_limits]

  [rate_limits.global]
  type = "ORDER_ACTION"
  aggregate = true
  request_limit = 5
  monitor_period = "60s"
  ban_period = "10s"
  high_water_mark = 3
  low_water_mark = 2
