symbols = [
  "^BTC-[0-9]{1,2}[A-Z]{3}[0-9]{2}$",  # futures
  "^ETH-[0-9]{1,2}[A-Z]{3}[0-9]{2}$",  # futures
  "^BTC(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^ETH(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^BTC(-USD[A-Z]?)?-DERIBIT-INDEX$",  # index
  "^ETH(-USD[A-Z]?)?-DERIBIT-INDEX$"   # index
]

[accounts]

  [accounts.A1]
  master = true
  #login = "2tZQEQRV"
  #secret = "saQaP6WmDefitTmd6DcAqnhJFtpC9eubZ3bzYm21af4"
  login = "Npu-0mAR"
  secret = "NExsbfKHjTqisZ9qJL8c2_15yk4brIrooxQ1n9uoW7M"
  symbols = ".*"

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "BTC-\\d{2}\\D{3}\\d{2}" ]

[rate_limits]

  [rate_limits.global]
    type = "ORDER_ACTION"
    aggregate = true
    request_limit = 100
    monitor_period = "10s"
    ban_period = "5m"

  [rate_limits.A1]
    type = "CREATE_ORDER"
    accounts = "A.*"
    request_limit = 30
    monitor_period = "1s"
    ban_period = "5m"

  [rate_limits.market_maker]
    type = "CREATE_ORDER"
    users = [ "trader" ]
    request_limit = 20
    monitor_period = "200ms"
    ban_period = "5m"
